version: '3.8'
services:
  postgres_test:
    image: postgres:15
    container_name: quarrycrm_postgres_test
    restart: unless-stopped
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: quarrycrm_test
    ports:
      - "5433:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data

volumes:
  postgres_test_data:
    name: quarrycrm_postgres_test_data
