name: CI - Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: quarrycrm_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U test -d quarrycrm_test" 
          --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Wait for Postgres
        run: |
          echo "Waiting for Postgres to be ready..."
          for i in {1..30}; do
            pg_isready -h localhost -p 5432 -U test -d quarrycrm_test && break || sleep 1
          done

      - name: Set TEST_DATABASE_URL
        run: echo "TEST_DATABASE_URL=postgresql://test:test@localhost:5432/quarrycrm_test" >> $GITHUB_ENV

      - name: Prisma generate
        run: npx prisma generate

      - name: Run tests
        run: npx vitest --run --reporter=dot

      - name: Upload vitest results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: vitest-report
          path: ./test-results || .
